---
# Example multi-node OpenStack deployment.

- name: Configure keepalived
  hosts: backend_servers
  sudo: True
  gather_facts: True
  roles:
    - keepalived

- name: Configure backend servers
  hosts: backend_servers
  sudo: True
  gather_facts: True
  vars_files:
    - "roles/analytics_api/defaults/main.yml"
    - "roles/edx_notes_api/defaults/main.yml"
  roles:
    - common
    - mongo
    - oraclejdk
    - elasticsearch
    - { role: 'mariadb', MARIADB_CREATE_DBS: 'yes' }

- name: Configure app servers
  hosts: app_servers
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
  pre_tasks:
    - name: Install memcached
      apt: pkg=memcached state=present
  roles:
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - supervisor
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - notifier
    - analytics_api
    - edx_notes_api
    - forum
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5" }
    - { role: 'xqueue', update_users: True }
    - certs
    - demo
